### ISSUE TITLE
No component factory found for CalendarModal

### ISSUE THREAD

**Issue by ygx305** [HsuanXyz/ion2-calendar#122]
Error: Uncaught (in promise): Error: No component factory found for CalendarModal. Did you add it to @NgModule.entryComponents?
Error: No component factory found for CalendarModal. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (http://localhost:8100/build/vendor.js:4142:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:8100/build/vendor.js:4206:19)
    at ModalCmp.ionViewPreLoad (http://localhost:8100/build/vendor.js:59858:36)
    at ModalImpl.ViewController._lifecycle (http://localhost:8100/build/vendor.js:23646:33)
    at ModalImpl.ViewController._preLoad (http://localhost:8100/build/vendor.js:23508:14)
    at OverlayPortal.NavControllerBase._preLoad (http://localhost:8100/build/vendor.js:54087:14)
    at OverlayPortal.NavControllerBase._viewInit (http://localhost:8100/build/vendor.js:53777:14)
    at http://localhost:8100/build/vendor.js:53588:23
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at OverlayPortal.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:53557:16)
    at OverlayPortal.NavControllerBase._failed (http://localhost:8100/build/vendor.js:53550:14)
    at http://localhost:8100/build/vendor.js:53597:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242

**Comment by iztan** [comment]
Hi @ygx305, did u manage to solve this issue?

**Comment by iztan** [comment]
@HsuanXyz I am not using lazy loading, any idea? Thank u in advance.

**Comment by mdali602** [comment]
I'm using lazy loading same issue here.

**Comment by vova1987** [comment]
Same problem here using Ionic-angular 3.9.4 and Lazy loaded pages

**Comment by Hanzofm** [comment]
For me the only way to solve it is adding it to app.module.ts imports AND into the lazy loaded page module

**Comment by okandeb** [comment]
any news? Not working Ionic 3 with lazy loading pages.

**Comment by aluferraz** [comment]
+1 Not working Ionic 3 with lazy loading pages.

**Comment by gabeklavans** [comment]
@Hanzofm That trick fixed it for me. Bless 🙌
