### ISSUE TITLE
Problem when run --prod -- release

### ISSUE THREAD

**Issue by williamsmjunior** [HsuanXyz/ion2-calendar#161]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ X] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[X ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[X ] help me

**Current behavior:**
When I do "ionic cordova run android --prod --release"
the result is:
Error: Metadata version mismatch for module **/node_modules/ion2-calendar/dist/calendar.model.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (**/node_modules/@angular/compiler/bundles/compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf **/node_modules/@angular/compiler/bundles/compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf **/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:14)
    at **/node_modules/@angular/compiler/bundles/compiler.umd.js:23023:30
    at Array.forEach (native)
    at extractProgramSymbols (**/node_modules/@angular/compiler/bundles/compiler.umd.js:23022:79)
    at AotCompiler.compileAll (**/node_modules/@angular/compiler/bundles/compiler.umd.js:22720:47)
    at CodeGenerator.codegen (**/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (**/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at Object.doCodegen (**/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)

The app run properly on debug mode.

Can you help me?

**Comment by aam-antonio** [comment]
Hi, I had the same problem. I think that the error comes because the angular engine on the plugin was changed to Angular 5 (version 4) and your project uses Angular 4 (version 3).

I solved it temporary modifying each metadata.json file on the plugin root folder, changing the version from 4 to 3.

These are the files I modified:
/node_modules/ion2-calendar/dist/calendar.controller.metadata.json
/node_modules/ion2-calendar/dist/calendar.model.metadata.json
/node_modules/ion2-calendar/dist/calendar.module.metadata.json
/node_modules/ion2-calendar/dist/config.metadata.json
/node_modules/ion2-calendar/dist/index.metadata.json
/node_modules/ion2-calendar/dist/service/calendar.service.metadata.json
/node_modules/ion2-calendar/dist/components/calendar.component.metadata.json
/node_modules/ion2-calendar/dist/components/calendar-week.component.metadata.json
/node_modules/ion2-calendar/dist/components/index.metadata.json
/node_modules/ion2-calendar/dist/components/month.component.metadata.json
/node_modules/ion2-calendar/dist/components/month-picker.component.metadata.json

I hope it gets solved soon.

**Comment by williamsmjunior** [comment]
Hi! Thank you! It solved my problem.

**Comment by nova974** [comment]
Hi, in my case, I downgrade to v2.1.5.
Like @aam-antonio said, it's a problem with some angular version

**Comment by aam-antonio** [comment]
You can upgrade your angular version to the latest (5.2.11) and the problem solves too.

There are no breaking changes, you can see it [here](https://update.angular.io/).

**Comment by nova974** [comment]
Yeah i know but it depends on other installed modules. 
I have to write some specs before update angular ^^'

**Comment by comadaihiep92** [comment]
i can't run ionic build --prod with ion2-calendar, it work with ionic build but i need --prod. Please help me fix it.

`$ ionic build --prod
> ng.cmd run app:build:production



ERROR in src/app/modals/popup/popup.page.ts:9:14 - error NG6007: The Component 'PopupPage' is declared by more than one NgModule.

9 export class PopupPage implements OnInit {
               ~~~~~~~~~

  src/app/bs-booking/bs-booking.module.ts:17:33
    17   declarations: [BsBookingPage, PopupPage, SorryPage],
                                       ~~~~~~~~~
    'PopupPage' is listed in the declarations of the NgModule 'BsBookingPageModule'.
  src/app/modals/popup/popup.module.ts:13:18
    13   declarations: [PopupPage],
                        ~~~~~~~~~
    'PopupPage' is listed in the declarations of the NgModule 'PopupPageModule'.
src/app/modals/sorry/sorry.page.ts:9:14 - error NG6007: The Component 'SorryPage' is declared by more than one NgModule.

9 export class SorryPage implements OnInit {
               ~~~~~~~~~

  src/app/bs-booking/bs-booking.module.ts:17:44
    17   declarations: [BsBookingPage, PopupPage, SorryPage],
                                                  ~~~~~~~~~
    'SorryPage' is listed in the declarations of the NgModule 'BsBookingPageModule'.
  src/app/modals/sorry/sorry.module.ts:18:18
    18   declarations: [SorryPage],
                        ~~~~~~~~~
    'SorryPage' is listed in the declarations of the NgModule 'SorryPageModule'.
src/app/account/account.page.html:30:17 - error TS2339: Property 'type' does not exist on type 'AccountPage'.

30         [type]="type"
                   ~~~~

  src/app/account/account.page.ts:5:16
    5   templateUrl: './account.page.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AccountPage.
src/app/account/account.page.html:32:20 - error TS2339: Property 'optionsBasic' does not exist on type 'AccountPage'.

32         [options]="optionsBasic"
                      ~~~~~~~~~~~~

  src/app/account/account.page.ts:5:16
    5   templateUrl: './account.page.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AccountPage.
src/app/account/account.page.html:28:22 - error TS2339: Property 'date' does not exist on type 'AccountPage'.

28         [(ngModel)]="date"
                        ~~~~

  src/app/account/account.page.ts:5:16
    5   templateUrl: './account.page.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AccountPage.
src/app/account/account.page.html:29:19 - error TS2339: Property 'onChange' does not exist on type 'AccountPage'.

29         (change)="onChange($event)"
                     ~~~~~~~~

  src/app/account/account.page.ts:5:16
    5   templateUrl: './account.page.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AccountPage.
src/app/account/account.page.html:28:22 - error TS2339: Property 'date' does not exist on type 'AccountPage'.

28         [(ngModel)]="date"
                        ~~~~

  src/app/account/account.page.ts:5:16
    5   templateUrl: './account.page.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AccountPage.
src/app/waiting/waiting.page.html:12:28 - error TS2554: Expected 1 arguments, but got 0.

12       <ion-button (click)="presentPopover()" class="btn waiting__button"
                              ~~~~~~~~~~~~~~

  src/app/waiting/waiting.page.ts:7:16
    7   templateUrl: "./waiting.page.html",
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component WaitingPage.

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:production exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

`Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\lanth.UNITEK\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
`
