### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'ion-calendar'.

### ISSUE THREAD

**Issue by ebgtestdotnet** [HsuanXyz/ion2-calendar#212]
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-calendar [(ngModel)]="dateRange"

                  [ERROR ->][options]="optionsRange"

                  [type]="type"
"): ng:///InvoiceViewModule/InvoiceView.html@64:18
Can't bind to 'type' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'type' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                  [options]="optionsRange"

                  [ERROR ->][type]="type"

                  [format]="'YYYY-MM-DD'">
"): ng:///InvoiceViewModule/InvoiceView.html@66:18
Can't bind to 'format' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'format' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                  [type]="type"

                  [ERROR ->][format]="'YYYY-MM-DD'">

    </ion-calendar>
"): ng:///InvoiceViewModule/InvoiceView.html@68:18
'ion-calendar' is not a known element:
1. If 'ion-calendar' is an Angular component, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <hr />

    [ERROR ->]<ion-calendar [(ngModel)]="dateRange"

                  [options]="optionsRange"
"): ng:///InvoiceViewModule/InvoiceView.html@62:4
Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ion-calendar [(ngModel)]="dateRange"

                  [ERROR ->][options]="optionsRange"

                  [type]="type"
"): ng:///InvoiceViewModule/InvoiceView.html@64:18
Can't bind to 'type' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'type' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                  [options]="optionsRange"

                  [ERROR ->][type]="type"

                  [format]="'YYYY-MM-DD'">
"): ng:///InvoiceViewModule/InvoiceView.html@66:18
Can't bind to 'format' since it isn't a known property of 'ion-calendar'.
1. If 'ion-calendar' is an Angular component and it has 'format' input, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                  [type]="type"

                  [ERROR ->][format]="'YYYY-MM-DD'">

    </ion-calendar>
"): ng:///InvoiceViewModule/InvoiceView.html@68:18
'ion-calendar' is not a known element:
1. If 'ion-calendar' is an Angular component, then verify that it is part of this module.
2. If 'ion-calendar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <hr />

    [ERROR ->]<ion-calendar [(ngModel)]="dateRange"

                  [options]="optionsRange"
"): ng:///InvoiceViewModule/InvoiceView.html@62:4
    at syntaxError (http://localhost:8100/build/vendor.js:99581:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:123764:19)
    at JitCompiler._parseTemplate (http://localhost:8100/build/vendor.js:133717:37)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:133692:23)
    at http://localhost:8100/build/vendor.js:133593:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:133593:19)
    at http://localhost:8100/build/vendor.js:133463:19
    at Object.then (http://localhost:8100/build/vendor.js:99570:77)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:133462:26)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:56182:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:56175:14)
    at http://localhost:8100/build/vendor.js:56222:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5124:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
Ionic Framework: 3.9.2
Ionic App Scripts: 3.2.0
Angular Core: 5.2.9
Angular Compiler CLI: 5.2.9
Node: 6.10.3
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by nkki** [comment]
how?

**Comment by Bimeon71** [comment]
Please, can you give us the solution?
